### ISSUE TITLE
Pixel polishes

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#21]
- [x] match checkboxes to what we're using in other NL sims
- [x] Make distance description larger and with more spacing under the accordion box
- [x] Make the legend (lower lefthand corner) have larger circles, letters, and artwork

**Comment by SaurabhTotey** [comment]
I was using the `NLCheckbox` from NLC, but I realized that I wasn't using `NLCheckboxGroup`, so I have now switched NLD over to using that so that these checkboxes should match what is being done in the other NL sims. I still need to adjust the distance description: it is currently so far up because the generic number line, when vertical, takes up most of the vertical space. I intend to reduce the height of the vertical number line to give more space to the distance description. I also still need to adjust the legend.

**Comment by SaurabhTotey** [comment]
The distance description is now larger and has been moved down. I had to move down the vertical number line even more and also move down the elevation bounds so that the distance description has space. I still need to adjust the legend at the bottom left.

**Comment by SaurabhTotey** [comment]
I have now made adjustments to all the legend items in the swap area at the bottom left.

I have made changes to address all of the items in this issue, so I will assign to @amanda-phet to review.

**Comment by amanda-phet** [comment]
All looks good to me!
