### ISSUE TITLE
LoL no longer pauses fully

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-distance#65]
For https://github.com/phetsims/qa/issues/683. Connected to https://github.com/phetsims/special-ops/issues/182, in which the sim did not appear properly paused. However, now items are interactable during this pause. This was seen with the Legends of Learning harness on 8/4/21.
@kathy-phet if this is a harness issue we may need to contact Legends of Learning again.
![notpausedlol](https://user-images.githubusercontent.com/41024075/128237111-4870a49c-931d-4b07-84a9-6022488384bf.gif)

**Comment by jbphet** [comment]
This doesn't appear to be a sim-specific issue, and there is already a general issue for the problem, see https://github.com/phetsims/special-ops/issues/182.  In that issue @kathy-phet says that it shouldn't block publication, and also that she'd contacted LoL and will report back.

Because this is not sim-specific, isn't blocking, and is being tracked elsewhere, I'm going to close this issue.

**Comment by amanda-phet** [comment]
Is this sim-specific, or related to the lol harness? Seems like it is a LoL issue, so I think this should be resolved over in https://github.com/phetsims/special-ops/issues/182 and not block this sim from being published.

**Comment by kathy-phet** [comment]
This behavior has changed on master. The sim should obey the pause command. This appears to be a common code change in the way the sim responds to the LOL harness.

**Comment by KatieWoe** [comment]
Ok, very odd new behavior. I went to check published sims to see how far back this might have been introduced. However, the brand-new NLD sim that showed the issue in rc does not seem to show it in the published version.

**Comment by kathy-phet** [comment]
Just a misspelling of the query parameter in the first test. Closing.
