### ISSUE TITLE
Directed Distance Arrow Scaling

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#7]
When the distance type is changed to directed distance, the shading between point controllers also draws an arrow. Currently, the arrow's scale is based off of the range of the number line (larger range means smaller arrow). @jbphet recommended that instead the scale of the arrow be scaled based off of the distance between point controllers similar to how force arrows act in atomic-interactions.
Currently, some sort of scaling for the arrow is necessary because when the number line range is -100 to 100, the point controllers can get really close to each other and the arrow looks distorted if it is too big and the points are close.
How should the arrow be scaled for the directed distance shading?

**Comment by amanda-phet** [comment]
This is a good question. My inclination is to keep the arrow the same all the time. I think a changing arrowhead would be strange feedback that might seem intentional or meaningful. It the main issue is from -100 to 100, how about you pick an arrowhead size that looks appropriate for each range and then I can review? 

So, smaller arrow for -100 to 100, and larger arrow for -10 to 10, and something in the middle for the middle range.

**Comment by amanda-phet** [comment]
I looked at phettest and the arrow for -100 to 100 is quite small. With the change in arrow size, maybe we also need to make the shading/weights of the distance slightly thinner?

**Comment by amanda-phet** [comment]
8/27/20 design meeting: 

We like an arrow size that is being used at [-10,10]. However on [-30,30] , once the tail is not visible, the arrow head + tail scale down in size (similar to Atomic Interactions) so that a tail is visible until you get two points that are one unit apart (at that point, it's ok to only see the arrowhead. This allows the arrowhead to be as large as possible). 

On [-100,100] we will do a similar scaling, but I'm not sure yet how small we'll make the arrowhead + tail.

**Comment by SaurabhTotey** [comment]
Right now, I have added atomic-interactions-like scaling to the arrows so that the head and tail scale so that the head is always at most half the whole width of the arrow. However, I haven't yet added a check for whether the range is -30 to 30 and whether the distance is 1 to make the arrow head the whole width of the distance. I will assign this issue to @amanda-phet to review the current scaling behaviour and confirm that I should add a check for the range and distance for 'custom' scalings like the one previously described. Currently, the scaling code is range-agnostic, but if we wanted to add range-based scalings, the ranges in the sim are [-10, 10], [-30, 30], [-100, 100], [-50, 50], and [-20, 20]. I can also perhaps add a temporary query parameter to be able to change the max ratio of the arrow head to the arrow's width (so that testing max ratios other than 0.5 would be easy).

**Comment by amanda-phet** [comment]
I'm not sure exactly how to interpret what you're saying... I think we talked about not scaling the arrowhead so that you can always see the direction it's pointing, not that we wanted custom solutions for different ranges (if I remember correctly). 

I am OK with how it currently is working. Sometimes the arrowhead can get really small, but it seems OK to me.

**Comment by amanda-phet** [comment]
Discussed in design 5/27/21 and we like the current behavior, no need to do a custom scaling. Thanks!
