### ISSUE TITLE
Panning is buggy

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-distance#87]
Originally found in Number Line Operations: https://github.com/phetsims/number-line-operations/issues/108

NLD will need a fix for it's specific use case as well.

**Comment by jessegreenberg** [comment]
I think this is fixed by a commit in number-line-common: https://github.com/phetsims/number-line-common/commit/3c5c9aaae87ae0ce90081685eb6d32e38de9b9a2

Tracked in https://github.com/phetsims/number-line-integers/issues/128, but leaving this issue open since a cherry-pick might be needed for this sim's release SHAs.

**Comment by marlitas** [comment]
This was cherry-picked for https://github.com/phetsims/qa/issues/1018. Feel free to close if all looks well.

**Comment by Nancy-Salpepi** [comment]
This is fixed on main but not fixed in rc.4.

**Comment by marlitas** [comment]
I must have missed a commit in the RC cherry-picks... checking

**Comment by Nancy-Salpepi** [comment]
Looks good in rc. 5!
